# Generated by Django 3.2.5 on 2021-07-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('rating', models.FloatField()),
                ('num_in_stock', models.IntegerField()),
                ('price', models.FloatField(default=1000.0)),
                ('publish_date', models.DateField()),
            ],
        ),
    ]
