# Generated by Django 3.2.5 on 2021-07-16 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publish_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='num_in_stock',
            new_name='stock',
        ),
    ]
