# Generated by Django 3.2.5 on 2021-07-17 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210717_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cupon',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.category'),
        ),
    ]
