# Generated by Django 3.2.5 on 2021-08-11 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simpleforms', '0002_director_filial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='filial',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='simpleforms.filial'),
        ),
    ]
