# Generated by Django 3.2.5 on 2021-08-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210815_2049'),
        ('shopping', '0005_auto_20210803_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='reduced_price',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=8)),
                ('stock', models.FloatField()),
                ('expires_in', models.DateTimeField()),
                ('category', models.ManyToManyField(to='store.SubCategory')),
            ],
        ),
    ]
