# Generated by Django 3.2.5 on 2021-08-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210815_2049'),
        ('shopping', '0006_auto_20210815_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('stock', models.FloatField()),
                ('expires_in', models.DateTimeField()),
                ('category', models.ManyToManyField(to='store.SubCategory')),
            ],
        ),
    ]
